version: '3'

# configure ingestion-edge for ci
services:
  web:
    build: .
    image: &image "${DOCKERHUB_REPO-ingestion-edge}:${CIRCLE_TAG-latest}"
    environment:
    - &route_table >-
      ROUTE_TABLE=[
        [
          "/stub/<suffix:path>",
          "projects/test/topics/stub_installer",
          ["GET"]
        ],
        # ## Proposed routes for account ecosystem telemetry
        # [
        #   "/submit/telemetry/<document_id:string>/<suffix:account-ecosystem.*>",
        #   "projects/test/topics/telemetry-ecosystem"
        # ],
        # [
        #   "/submit/<namespace:string>/<suffix:account-ecosystem.*>",
        #   "projects/test/topics/structured-ecosystem"
        # ],
        [
          "/submit/telemetry/<suffix:path>",
          "projects/test/topics/telemetry"
        ],
        [
          "/submit/sslreports",
          "projects/test/topics/tls_error_reports",
          ["post", "put"]
        ],
        [
          "/submit/<suffix:path>",
          "projects/test/topics/ingestion",
          ["PoSt", "pUt"]
        ],
        [
          "/submit",
          "projects/test/topics/ingestion"
        ]
      ]
  pubsub:
    image: *image
    command: python -m pubsub_emulator
    environment:
      PORT: 8085
  test:
    image: *image
    command:
    - bin/pytest-all
    environment:
    - *route_table
